function Hd = FIR_500_200
%FIR_500_200 Returns a discrete-time filter object.
% MATLAB Code
% Generated by MATLAB(R) 8.5 and the Signal Processing Toolbox 7.0.
% Generated on: 05-Oct-2018 13:49:47
 
% Equiripple Highpass filter designed using the FIRPM function.
 
% All frequency values are normalized to 1.
 
N     = 20;   % Order
Fstop = 0.05;  % Stopband Frequency
Fpass = 0.1;   % Passband Frequency
Wstop = 1;     % Stopband Weight
Wpass = 1;     % Passband Weight
dens  = 20;    % Density Factor
 
% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fstop Fpass 1], [0 0 1 1], [Wstop Wpass], {dens});
Hd = dfilt.dffir(b);
 
% [EOF]
