function [fit]=spec_fitBOLD(fit)
fit.whatcombine=0;
fit.howcombine=0;
switch fit.models
    case 'IS'
        fit.scans='behav'; %which_scans='behav'; %Use Brain scans at the time of the modelled behavior only
    case 'RL'
        fit.scans='all';
    case 'RLIS'
        fit.scans='all';
end
switch fit.models
    case 'RL'
        fprintf('\n Using Reinforcement Learning ROI \n ');
        if strcmp(fit.scans,'behav')
            if behav==0
                fprintf(' \n Cannot use Brain scans at the time of the behvioural report to model ROIs at the same time \n the procedure is not valid statistically')
            end
        elseif strcmp(fit.scans,'all')
            fprintf(' \n Using all the brain scans to model either another ROI or a behavioural report');
            if fit.combine
                fit.whatcombine=[1 2; 3 4; 5 6; 7 8;9 10];%you need to specify this vector, each group of ROIs must be in the same row.
                fit.howcombine='mean'; %possible options for now are mean or median.
            end
            if fit.social_ROIs==0
                fit.ROIs={'Amygdala Lt_roi.mat','Amygdala Rt_roi.mat',...
                    'VS Lt_roi.mat','VS Rt_roi.mat',...
                     'BA13_Lt_roi.mat','BA13_Rt_roi.mat',...
                     'BA11m Lt_roi.mat','BA11m Rt_roi.mat',...
                     'BA14m Lt_roi.mat','BA14m Rt_roi.mat',...
                      'BA25 Lt_roi.mat','BA25 Rt_roi.mat',...
                      'BA32sg_Lt_roi.mat','BA32sg_Rt_roi.mat',...
                    'VS Lt_roi.mat','VS Rt_roi.mat',...
                    'BA24cd Lt_roi.mat','BA24cd Rt_roi.mat',...
                    'BA32p Lt_roi.mat','BA32p Rt_roi.mat'};
                fit.timings={'Min EV','Min EV','Min EV',...
                    'Min EV','Min EV','Min EV',...
                    'Min EV','Min EV','Min EV',...
                    'Min EV','Min EV','Min EV','Min EV',...
                    'Min EV',...
                    'PE','PE','PE','PE',...
                    'PE','PE'};
            elseif fit.social_ROIs==1
                fit.ROIs={'Amygdala Lt_roi.mat','Amygdala Rt_roi.mat',...
                    'VS Lt_roi.mat','VS Rt_roi.mat',...
                    'BA13_Lt_roi.mat','BA13_Rt_roi.mat',...
                    'BA11m Lt_roi.mat','BA11m Rt_roi.mat',...
                    'BA14m Lt_roi.mat','BA14m Rt_roi.mat',...
                    'BA25 Lt_roi.mat','BA25 Rt_roi.mat',...
                    'BA32sg_Lt_roi.mat','BA32sg_Rt_roi.mat',...
                    'VS Lt_roi.mat','VS Rt_roi.mat',...
                    'BA24cd Lt_roi.mat','BA24cd Rt_roi.mat',...
                    'BA32p Lt_roi.mat','BA32p Rt_roi.mat',...
                    'BA23d_Lt_roi.mat','BA23d_Rt_roi.mat',...
                    'BA31 Lt_roi.mat','BA31 Rt_roi.mat',...
                    'BA9m Lt_roi.mat','BA9m Rt_roi.mat',...
                    'aSTS_Lt_roi.mat','aSTS_Rt_roi.mat',...
                    'BA39rv_Lt_roi.mat','BA39rv_Rt_roi.mat',...
                    'BA23d_Lt_roi.mat','BA23d_Rt_roi.mat',...
                    'BA31 Lt_roi.mat','BA31 Rt_roi.mat',...
                    'BA9m Lt_roi.mat','BA9m Rt_roi.mat',...
                    'aSTS_Lt_roi.mat','aSTS_Rt_roi.mat',...
                    'BA39rv_Lt_roi.mat','BA39rv_Rt_roi.mat'};
                
                fit.timings={'Min EV','Min EV','Min EV',...
                    'Min EV','Min EV','Min EV',...
                    'Min EV','Min EV','Min EV','Min EV',...
                    'Min EV','Min EV','Min EV','Min EV',...
                    'PE','PE','PE','PE',...
                    'PE','PE',...
                    'Min EV','Min EV','Min EV','Min EV','Min EV',...
                    'Min EV','Min EV','Min EV','Min EV','Min EV',...
                    'PE','PE','PE','PE','PE',...
                    'PE','PE','PE','PE','PE'};
                
            elseif fit.social_ROIs==2
                fit.ROIs={'BA23d_Lt_roi.mat','BA23d_Rt_roi.mat',...
                    'BA31 Lt_roi.mat','BA31 Rt_roi.mat',...
                    'BA9m Lt_roi.mat','BA9m Rt_roi.mat',...
                    'aSTS_Lt_roi.mat','aSTS_Rt_roi.mat',...
                    'BA39rv_Lt_roi.mat','BA39rv_Rt_roi.mat',...
                    'BA23d_Lt_roi.mat','BA23d_Rt_roi.mat',...
                    'BA31 Lt_roi.mat','BA31 Rt_roi.mat',...
                    'BA9m Lt_roi.mat','BA9m Rt_roi.mat',...
                    'aSTS_Lt_roi.mat','aSTS_Rt_roi.mat',...
                    'BA39rv_Lt_roi.mat','BA39rv_Rt_roi.mat'};
                
                fit.timings={'Min EV','Min EV','Min EV','Min EV','Min EV','Min EV','Min EV',...
                    'Min EV','Min EV','Min EV','Min EV','Min EV','Min EV','Min EV',...
                    'PE','PE','PE','PE','PE','PE','PE',...
                    'PE','PE','PE','PE','PE','PE','PE'};
            end
            for at_time_fill=1:size(fit.ROIs,2)
                if fit.condition_before
                    fit.timings{2,at_time_fill}= fit.condition_before;
                end
            end
        end
        fit.TargetBOLD='Subgenual vmPFC & mOFC Bi_roi.mat';
        fit.Target_timing{1,1}='happiness';
        if fit.condition_before
            fit.Target_timing{2,1}=fit.condition_before;
        end
    case 'RL-Ct'
        fprintf('\n Using Reinforcement Learning ROI \n ');
        if strcmp(fit.scans,'behav')
            if fit.behav==1
                if fit.combine
                    fit.whatcombine=[1 2; 3 4; 5 6; 7 8];%you need to specify this vector, each group of ROIs must be in the same row.
                    fit.howcombine='mean'; %possible options for now are mean or median.
                end
                fprintf(' \n predicting a behavioural report from brain scans at time of the report');
                fit.ROIs={'msOccG_Lt_roi.mat','msOccG_Rt_roi.mat',...
                    'OPC_Lt_roi.mat','OPC_Rt_roi.mat',...
                    'mOccG_Lt_roi.mat','mOccG_Rt_roi.mat',...
                    'msOccG_Lt_roi.mat','msOccG_Rt_roi.mat',...
                    'OPC_Lt_roi.mat','OPC_Rt_roi.mat',...
                    'mOccG_Lt_roi.mat','mOccG_Rt_roi.mat'};
                fit.timings=cell(1,size(fit.ROIs,2));
                for at_time_fill=1:size(fit.ROIs,2)
                    fit.timings{1,at_time_fill}='happiness';
                    if fit.condition_before
                        fit.timings{2,at_time_fill}= fit.condition_before;
                    end
                end
            end
        elseif strcmp(fit.scans,'behav')
            if behav==0
                fprintf(' \n Cannot use Brain scans at the time of the behvioural report to model fit.ROIs at the same time \n the procedure is not valid statistically')
            end
        elseif strcmp(fit.scans,'all')
            fprintf(' \n Using all the brain scans to model either another ROI or a behavioural report');
            if fit.combine
                fit.whatcombine=[1 2; 3 4; 5 6; 7 8;9 10];%you need to specify this vector, each group of ROIs must be in the same row.
                fit.howcombine='mean'; %possible options for now are mean or median.
            end
            if fit.social_ROIs==0
                fit.ROIs={'msOccG_Lt_roi.mat','msOccG_Rt_roi.mat',...
                    'OPC_Lt_roi.mat','OPC_Rt_roi.mat',...
                    'mOccG_Lt_roi.mat','mOccG_Rt_roi.mat',...
                    'OPC_Lt_roi.mat','OPC_Rt_roi.mat',...
                    'mOccG_Lt_roi.mat','mOccG_Rt_roi.mat'};
                fit.timings={'Min EV','Min EV','Min EV',...
                    'Min EV','Min EV','Min EV',...
                    'PE','PE','PE','PE'};
            elseif fit.social_ROIs==1
                fit.ROIs={'msOccG_Lt_roi.mat','msOccG_Rt_roi.mat',...
                    'OPC_Lt_roi.mat','OPC_Rt_roi.mat',...
                    'mOccG_Lt_roi.mat','mOccG_Rt_roi.mat',...
                    'OPC_Lt_roi.mat','OPC_Rt_roi.mat',...
                    'mOccG_Lt_roi.mat','mOccG_Rt_roi.mat',...
                    'V5-MT_Lt_roi.mat', 'V5-MT_Rt_roi.mat',...
                    'BA2_Lt_roi.mat','BA2_Rt_roi.mat',...
                    'BA1-2-3tru_Lt_roi.mat','BA1-2-3tru_Rt_roi.mat',...
                    'BA1-2-3tonIa_Lt_roi.mat','BA1-2-3tonIa_Rt_roi.mat',...
                    'V5-MT_Lt_roi.mat', 'V5-MT_Rt_roi.mat',...
                    'BA2_Lt_roi.mat','BA2_Rt_roi.mat',...
                    'BA1-2-3tru_Lt_roi.mat','BA1-2-3tru_Rt_roi.mat',...
                    'BA1-2-3tonIa_Lt_roi.mat','BA1-2-3tonIa_Rt_roi.mat'};
                
                fit.timings={'Min EV','Min EV','Min EV',...
                    'Min EV','Min EV','Min EV',...
                    'PE','PE','PE','PE',...
                    'Min EV','Min EV','Min EV','Min EV','Min EV','Min EV','Min EV','Min EV',...
                    'PE','PE','PE','PE','PE','PE','PE','PE'};
            end
            for at_time_fill=1:size(fit.ROIs,2)
                if fit.condition_before
                    fit.timings{2,at_time_fill}= fit.condition_before;
                end
            end
        end
        fit.TargetBOLD='Subgenual vmPFC & mOFC Bi_roi.mat';
        fit.Target_timing{1,1}='happiness';
        if fit.condition_before
            fit.Target_timing{2,1}=fit.condition_before;
        end
        
    case 'IS'
        
        fprintf(' \n Using Incentive Salience ROI \n ');
        if strcmp(fit.scans,'behav')
            if fit.behav==1
                if fit.combine
                    fit.whatcombine=[1 2; 3 4; 5 6;7 8;9 10];%you need to specify this vector, each group of ROIs must be in the same row.
                    fit.howcombine='mean'; %possible options for now are mean or median.
                end
                fprintf('predicting a behavioural report from brain scans at time of the report');
                if fit.social_ROIs==0
                    fit.ROIs={'VPe Ant Lt_roi.mat','VPe Ant Rt_roi.mat',...
                        'VPe Post Lt_roi.mat','VPe Post Rt_roi.mat',...
                         'VS Lt_roi.mat','VS Rt_roi.mat',...
                         'dIa Lt_roi.mat','dIa Rt_roi.mat',...
                         'vIa Lt_roi.mat','vIa Rt_roi.mat',...
                      'BA32sg_Lt_roi.mat','BA32sg_Rt_roi.mat',...
                        'BA25 Lt_roi.mat','BA25 Rt_roi.mat'};
                    fit.timings=cell(1,size(fit.ROIs,2));
                    for at_time_fill=1:size(fit.ROIs,2)
                        fit.timings{1,at_time_fill}='happiness';
                        if fit.condition_before
                            fit.timings{2,at_time_fill}= fit.condition_before;
                        end
                    end
                elseif fit.social_ROIs==1
                    fit.ROIs={'VPe Ant Lt_roi.mat','VPe Ant Rt_roi.mat',...
                        'VPe Post Lt_roi.mat','VPe Post Rt_roi.mat',...
                       'VS Lt_roi.mat','VS Rt_roi.mat',...
                         'dIa Lt_roi.mat','dIa Rt_roi.mat',...
                         'vIa Lt_roi.mat','vIa Rt_roi.mat',...
                         'BA25 Lt_roi.mat','BA25 Rt_roi.mat',...
                         'BA32sg_Lt_roi.mat','BA32sg_Rt_roi.mat',...
                        'BA23d_Lt_roi.mat','BA23d_Rt_roi.mat',...
                        'BA44v_Lt_roi.mat','BA44v_Rt_roi.mat',...
                        'BA31 Lt_roi.mat','BA31 Rt_roi.mat',...
                        'BA9m Lt_roi.mat','BA9m Rt_roi.mat'};
                    fit.timings={'happiness','happiness',...
                        'happiness','happiness',...
                        'happiness','happiness',...
                        'happiness','happiness',...
                         'happiness','happiness',...
                        'happiness','happiness',...
                        'happiness','happiness',...
                        'happiness','happiness',...
                        'happiness','happiness'};
              elseif fit.social_ROIs==2
                    fit.ROIs={'BA23d_Lt_roi.mat','BA23d_Rt_roi.mat',...
                        'BA44v_Lt_roi.mat','BA44v_Rt_roi.mat',...
                        'BA31 Lt_roi.mat','BA31 Rt_roi.mat',...
                        'BA9m Lt_roi.mat','BA9m Rt_roi.mat'};
                    fit.timings={'happiness','happiness',...
                        'happiness','happiness',...
                        'happiness','happiness',...
                        'happiness','happiness'};
                end
                
            end
        elseif strcmp(fit.scans,'behav')
            if fit.behav==0
                fprintf(' \n Cannot use Brain scans at the time of the behvioural report to model ROIs at the same time \n the procedure is not valid statistically')
            end
        elseif strcmp(fit.scans,'all')
            fprintf(' \n Using all the brain scans to model either another ROI or a behavioural report');
            if fit.combine
                fit.whatcombine=[1 2; 3 4; 5 6;7 8;9 10];%you need to specify this vector, each group of ROIs must be in the same row.
                fit.howcombine='mean'; %possible options for now are mean or median.
            end
            fit.ROIs={ 'VS Med Ant Lt_roi.mat','VS Med Ant Rt_roi.mat',...
                'VPe Ant Lt_roi.mat','VPe Ant Rt_roi.mat',...
                'ACC Lt_roi.mat','ACC Rt_roi.mat',...
                'VS Lt_roi.mat','VS Rt_roi.mat',...
                'ACC Lt_roi.mat','ACC Rt_roi.mat'};
            fit.timings={'Min EV','Min EV',...
                'Min EV','Min EV',...
                'PE','PE',...
                'PE','PE'};
            for at_time_fill=1:size(fit.ROIs,2)
                if fit.condition_before
                    fit.timings{2,at_time_fill}= fit.condition_before;
                end
            end
        end
        
        fit.TargetBOLD='Subgenual vmPFC & mOFC Bi_roi.mat'; %respecify that
        fit.Target_timing{1,1}='happiness';
        if fit.condition_before
            fit.Target_timing{2,1}=fit.condition_before;
        end
        
    case 'CS'
        fprintf(' \n Using a Custom built combination of ROIs \n ')
        if strcmp(fit.scans,'behav')
            if fit.behav==1
                if fit.combine
                    fit.whatcombine=[1 2; 3 4; 5 6; 7 8; 9 10];%you need to specify this vector, each group of ROIs must be in the same row.
                    fit.howcombine='mean'; %possible options for now are mean or median.
                end
                fprintf('\n predicting a behavioural report from brain scans at time of the report');
                fit.ROIs={'VS Med Ant Lt_roi.mat','VS Med Ant Rt_roi.mat'...
                    'Insula Lt_roi.mat','Insula Rt_roi.mat',...
                    'BA32p_Lt_roi.mat','BA32p_Rt_roi.mat',...
                    'VPe Ant Lt_roi.mat','VPe Ant Rt_roi.mat',...
                    'VPe Post Lt_roi.mat','VPe Post Rt_roi.mat'};
                
                
                %                 'ACC Lt_roi.mat','ACC Rt_roi.mat',...
                %                 'Amygdala Lt_roi.mat','Amygdala Rt_roi.mat',...
                %                 'BA24rv_Rt_roi.mat','BA24rv_Lt_roi.mat',...
                %                 'BA32sg_Lt_roi.mat','BA32sg_Rt_roi.mat',...
                %                 'BA13_Lt_roi.mat','BA13_Rt_roi.mat'};
                fit.timings=cell(1,size(fit.ROIs,2));
                for at_time_fill=1:size(fit.ROIs,2)
                    fit.timings{1,at_time_fill}='happiness';
                    %                 if fit.condition_before
                    %                     fit.timings{2,at_time_fill}= fit.condition_before;
                    %                 end
                end
            end
        elseif strcmp(fit.scans,'behav')
            if fit.behav==0
                fprintf('\n Cannot use Brain scans at the time of the behvioural report to model ROIs at the same time \n the procedure is not valid statistically')
            end
        elseif strcmp(fit.scans,'all')
            fprintf('\n Using all the brain scans to model either another ROI or a behavioural report');
            fit.ROIs={'VS Med Ant Lt_roi.mat','VS Med Ant Rt_roi.mat'...
                'Amygdala Lt_roi.mat','Amygdala Rt_roi.mat'...
                'ACC Lt_roi.mat','ACC Rt_roi.mat',...
                'Pos RPE -16_0_70_roi.mat','Pos RPE -20_2_-22_roi.mat'...
                'Pos RPE -23_2_0_roi.mat','Pos RPE 4_8_38_roi.mat',...
                'Pos RPE 25_3_0_roi.mat','Pos RPE 56_12_18_roi.mat',...
                'Neg RPE -24_-4_6_roi.mat','Neg RPE -30_14_64_roi.mat',...
                'Neg RPE -30_28_6_roi.mat','Neg RPE -42_-8_48_roi.mat',...
                'Neg RPE 4_2_60_roi.mat'};
            fit.timings={'Min EV','Min EV',...
                'Min EV','Min EV',...
                'Min EV','Min EV',...
                'PE Pos','PE Pos','PE Pos','PE Pos','PE Pos','PE Pos'...
                'PE Neg','PE Neg','PE Neg','PE Neg','PE Neg'};
            for at_time_fill=1:size(fit.ROIs,2)
                if fit.condition_before
                    fit.timings{2,at_time_fill}= fit.condition_before;
                end
            end
        end
        fit.TargetBOLD='Subgenual vmPFC & mOFC Bi_roi.mat'; %respecify that
        fit.Target_timing{1,1}='happiness';
        if fit.condition_before
            fit.Target_timing{2,1}=fit.condition_before;
        end
        
        
    case 'RLIS'
        
        fprintf(' \n Using Reinforcement learning and Incentive Salience ROI \n ');
        if strcmp(fit.scans,'behav')
            if behav==0
                fprintf(' \n Cannot use Brain scans at the time of the behvioural report to model ROIs at the same time \n the procedure is not valid statistically')
            end
        elseif strcmp(fit.scans,'all')
            fprintf(' \n Using all the brain scans to model either another ROI or a behavioural report');
            if fit.combine
                fit.whatcombine=[1 2; 3 4; 5 6;7 8;9 10];%you need to specify this vector, each group of ROIs must be in the same row.
                fit.howcombine='mean'; %possible options for now are mean or median.
            end
            if fit.social_ROIs==0
                fit.ROIs={'Amygdala Lt_roi.mat','Amygdala Rt_roi.mat',...
                    'ACC Lt_roi.mat','ACC Rt_roi.mat',...
                    'VS Med Ant Lt_roi.mat','VS Med Ant Rt_roi.mat',...
                    'VS Lt_roi.mat','VS Rt_roi.mat',...
                    'ACC Lt_roi.mat','ACC Rt_roi.mat'...
                    'VPe Ant Lt_roi.mat','VPe Ant Rt_roi.mat',...
                    'VPe Post Lt_roi.mat','VPe Post Rt_roi.mat',...
                    'VS Med Ant Lt_roi.mat','VS Med Ant Rt_roi.mat',...
                    'BA32sg_Lt_roi.mat','BA32sg_Rt_roi.mat',...
                    'BA13_Lt_roi.mat','BA13_Rt_roi.mat'};
                fit.timings={'Min EV','Min EV','Min EV',...
                    'Min EV','Min EV','Min EV',...
                    'PE','PE','PE','PE'...
                    'happiness','happiness',...
                    'happiness','happiness',...
                    'happiness','happiness',...
                    'happiness','happiness',...
                    'happiness','happiness'};
            elseif fit.social_ROIs==1
                fit.ROIs={'Amygdala Lt_roi.mat','Amygdala Rt_roi.mat',...
                    'ACC Lt_roi.mat','ACC Rt_roi.mat',...
                    'VS Lt_roi.mat','VS Rt_roi.mat',...
                    'VS Lt_roi.mat','VS Rt_roi.mat',...
                    'ACC Lt_roi.mat','ACC Rt_roi.mat',...
                    'BA23d_Lt_roi.mat','BA23d_Rt_roi.mat',...
                    'BA44v_Lt_roi.mat','BA44v_Rt_roi.mat',...
                    'BA31 Lt_roi.mat','BA31 Rt_roi.mat',...
                    'BA9m Lt_roi.mat','BA9m Rt_roi.mat',...
                    'BA23d_Lt_roi.mat','BA23d_Rt_roi.mat',...
                    'BA44v_Lt_roi.mat','BA44v_Rt_roi.mat',...
                    'BA31 Lt_roi.mat','BA31 Rt_roi.mat',...
                    'BA9m Lt_roi.mat','BA9m Rt_roi.mat',...
                    'VPe Ant Lt_roi.mat','VPe Ant Rt_roi.mat',...
                    'VPe Post Lt_roi.mat','VPe Post Rt_roi.mat',...
                    'VS Med Ant Lt_roi.mat','VS Med Ant Rt_roi.mat',...
                    'BA32sg_Lt_roi.mat','BA32sg_Rt_roi.mat',...
                    'BA13_Lt_roi.mat','BA13_Rt_roi.mat',...
                    'BA23d_Lt_roi.mat','BA23d_Rt_roi.mat',...
                    'BA44v_Lt_roi.mat','BA44v_Rt_roi.mat',...
                    'BA31 Lt_roi.mat','BA31 Rt_roi.mat',...
                    'BA9m Lt_roi.mat','BA9m Rt_roi.mat'};
                
                fit.timings={'Min EV','Min EV','Min EV',...
                    'Min EV','Min EV','Min EV',...
                    'PE','PE','PE','PE',...
                    'Min EV','Min EV','Min EV','Min EV',...
                    'Min EV','Min EV','Min EV','Min EV',...
                    'PE','PE','PE','PE',...
                    'PE','PE','PE','PE',...
                    'happiness','happiness',...
                    'happiness','happiness',...
                    'happiness','happiness',...
                    'happiness','happiness',...
                    'happiness','happiness',...
                    'happiness','happiness',...
                    'happiness','happiness',...
                    'happiness','happiness',...
                    'happiness','happiness'};
            end
        end
        
        fit.TargetBOLD='Subgenual vmPFC & mOFC Bi_roi.mat'; %respecify that
        fit.Target_timing{1,1}='happiness';
        if fit.condition_before
            fit.Target_timing{2,1}=fit.condition_before;
        end
        
    case 'CS2' %time of options shown and time of rating of happiness are consdidered timings for activations of regions encoding pleasure directly
        %PE is not divided into positive and negative
        
        fprintf(' \n Using Reinforcement learning and Incentive Salience ROI \n ');
        if strcmp(fit.scans,'behav')
            if fit.behav==0
                fprintf(' \n Cannot use Brain scans at the time of the behvioural report to model ROIs at the same time \n the procedure is not valid statistically')
            end
        elseif strcmp(fit.scans,'all')
            fprintf(' \n Using all the brain scans to model either another ROI or a behavioural report');
            if fit.combine
                fit.whatcombine=[1 2; 3 4; 5 6;7 8;9 10];%you need to specify this vector, each group of ROIs must be in the same row.
                fit.howcombine='mean'; %possible options for now are mean or median.
            end
            if fit.social_ROIs==0
                fit.ROIs={'Amygdala Lt_roi.mat','Amygdala Rt_roi.mat',...%options shown
                    'ACC Lt_roi.mat','ACC Rt_roi.mat',...
                    'VS Med Ant Lt_roi.mat','VS Med Ant Rt_roi.mat'...
                    'VPe Ant Lt_roi.mat','VPe Ant Rt_roi.mat',...
                    'VPe Post Lt_roi.mat','VPe Post Rt_roi.mat'...
                    'Insula Lt_roi.mat','Insula Rt_roi.mat',...
                    'BA32sg_Lt_roi.mat','BA32sg_Rt_roi.mat',...
                    'VS Lt_roi.mat','VS Rt_roi.mat',...%Results shown
                    'ACC Lt_roi.mat','ACC Rt_roi.mat'...
                    'Amygdala Lt_roi.mat','Amygdala Rt_roi.mat',...%rating happiness
                    'VS Med Ant Lt_roi.mat','VS Med Ant Rt_roi.mat'...
                    'ACC Lt_roi.mat','ACC Rt_roi.mat',...
                    'Insula Lt_roi.mat','Insula Rt_roi.mat',...
                    'BA32sg_Lt_roi.mat','BA32sg_Rt_roi.mat',...
                    'VPe Ant Lt_roi.mat','VPe Ant Rt_roi.mat',...
                    'VPe Post Lt_roi.mat','VPe Post Rt_roi.mat'};
                fit.timings={'Min EV','Min EV','Min EV',...
                    'Min EV','Min EV','Min EV',...
                    'Min EV','Min EV',...
                    'Min EV','Min EV',...
                    'Min EV','Min EV',...
                    'Min EV','Min EV',...
                    'PE','PE','PE','PE'...
                    'happiness','happiness',...
                    'happiness','happiness',...
                    'happiness','happiness',...
                    'happiness','happiness',...
                    'happiness','happiness',...
                    'happiness','happiness',...
                    'happiness','happiness'};
            elseif fit.social_ROIs==1
                fit.ROIs={'Amygdala Lt_roi.mat','Amygdala Rt_roi.mat',...%options shown
                    'ACC Lt_roi.mat','ACC Rt_roi.mat',...
                    'VS Med Ant Lt_roi.mat','VS Med Ant Rt_roi.mat'...
                    'VPe Ant Lt_roi.mat','VPe Ant Rt_roi.mat',...
                    'VPe Post Lt_roi.mat','VPe Post Rt_roi.mat'...
                    'Insula Lt_roi.mat','Insula Rt_roi.mat',...
                    'BA32sg_Lt_roi.mat','BA32sg_Rt_roi.mat',...
                    'BA5m Lt_roi.mat','BA5m Rt_roi.mat',... %Social ROIs/options shown
                    'BA7m Lt_roi.mat','BA7m Rt_roi.mat',...
                    'BA23d_Lt_roi.mat','BA23d_Rt_roi.mat',...
                    'BA44v_Lt_roi.mat','BA44v_Rt_roi.mat',...
                    'BA31 Lt_roi.mat','BA31 Rt_roi.mat',...
                    'BA9m Lt_roi.mat','BA9m Rt_roi.mat',...
                    'BA10m Lt_roi.mat','BA10m Rt_roi.mat',...
                    'VS Lt_roi.mat','VS Rt_roi.mat',...%Results shown
                    'ACC Lt_roi.mat','ACC Rt_roi.mat'...
                    'BA5m Lt_roi.mat','BA5m Rt_roi.mat',...%Social ROIs/results shown
                    'BA7m Lt_roi.mat','BA7m Rt_roi.mat',...
                    'BA23d_Lt_roi.mat','BA23d_Rt_roi.mat',...
                    'BA44v_Lt_roi.mat','BA44v_Rt_roi.mat',...
                    'BA31 Lt_roi.mat','BA31 Rt_roi.mat',...
                    'BA9m Lt_roi.mat','BA9m Rt_roi.mat',...
                    'BA10m Lt_roi.mat','BA10m Rt_roi.mat'...
                    'Amygdala Lt_roi.mat','Amygdala Rt_roi.mat',...%Happiness rating
                    'ACC Lt_roi.mat','ACC Rt_roi.mat',...
                    'VS Med Ant Lt_roi.mat','VS Med Ant Rt_roi.mat'...
                    'VPe Ant Lt_roi.mat','VPe Ant Rt_roi.mat',...
                    'VPe Post Lt_roi.mat','VPe Post Rt_roi.mat'...
                    'Insula Lt_roi.mat','Insula Rt_roi.mat',...
                    'BA32sg_Lt_roi.mat','BA32sg_Rt_roi.mat'};
                
                fit.timings={'Min EV','Min EV','Min EV','Min EV','Min EV','Min EV','Min EV',...
                    'Min EV','Min EV','Min EV','Min EV','Min EV','Min EV','Min EV',...
                    'Min EV','Min EV','Min EV','Min EV','Min EV','Min EV','Min EV',...
                    'Min EV','Min EV','Min EV','Min EV','Min EV','Min EV','Min EV',...
                    'PE','PE','PE','PE',...
                    'PE','PE','PE','PE','PE','PE','PE',...
                    'PE','PE','PE','PE','PE','PE','PE'...
                    'happiness','happiness',...
                    'happiness','happiness',...
                    'happiness','happiness',...
                    'happiness','happiness',...
                    'happiness','happiness',...
                    'happiness','happiness',...
                    'happiness','happiness'};
            end
            for at_time_fill=1:size(fit.ROIs,2)
                if fit.condition_before
                    fit.timings{2,at_time_fill}= fit.condition_before;
                end
            end
        end
        
        fit.TargetBOLD='Subgenual vmPFC & mOFC Bi_roi.mat'; %respecify that
        fit.Target_timing{1,1}='happiness';
        if fit.condition_before
            fit.Target_timing{2,1}=fit.condition_before;
        end
        
end
dup_idx=find(strcmp(fit.ROIs,fit.TargetBOLD));
if ~isempty(dup_idx)
    dup_idx_timing=find(strcmp(fit.timings{dup_idx},fit.Target_timing));
    if ~isempty(dup_idx_timing)
        fprintf('\n I found the same ROI BOLD at the same time on both sides...\n of the modelling equation. This will give you a fake R squared of 1 \n removing from the left side of the equation.... \n')
        rest_idx=find(~strcmp(fit.ROIs,fit.TargetBOLD));
        fit.ROIs={fit.ROIs{1,[rest_idx]}};
        for timings_i= 1: size(fit.timings,1)
            for rest_idx_i=1: size(rest_idx,2)
                timings_corct{timings_i,rest_idx_i}=fit.timings{timings_i,rest_idx(rest_idx_i)};
            end
        end
    end
else
    timings_corct=fit.timings;
end
fit.timings=timings_corct;
end
