function filter=BOLD_filt(n,c)
max=size(n,1);
order=round(max/3)-2;
if order >50; order=50;end
if exist('c','var') && strcmp(c,'LSD')
    filter=designfilt('Highpassfir',...
  'StopbandFrequency',0.03,'PassbandFrequency',0.035','FilterOrder', order,...
   'DesignMethod','equiripple');
else
filter=designfilt('Bandpassfir',...
  'Cutofffrequency1',0.12,'Cutofffrequency2',0.35','FilterOrder', order...
   );
end
% filter = designfilt('highpassfir', 'FilterOrder', 50, ...
%                     'PassbandFrequency', 0.2, 'PassbandRipple', 0.001 ...
%                     );
%  if size(filter.Coefficients,2) > (max/3)-2 || c==2
%      filter=designfilt('highpassfir','FilterOrder', round(max/3)-2,...
%    'StopbandFrequency',0.001,'PassbandFrequency',0.2,...
%     'DesignMethod','Equiripple'...
%      );
%  end
end
